### ISSUE TITLE
Orphaned Watchers Fail to Get Removed

### ISSUE THREAD

**Issue by sethyes** [elasticfence/kaae#33]
1. Issue Description:
When deleting watchers through the GUI, you receive a notification that it was successfully deleted, however they simply get orphaned and not completely deleted, as can be seen in the Kibana logs;

kibana.stdout:
<code> 
{"type":"log","@timestamp":"2016-10-05T23:24:00Z","tags":["status","debug","KaaE"],"pid":42867,"message":"Reloading Watchers..."}
{"type":"log","@timestamp":"2016-10-05T23:24:00Z","tags":["status","info","KaaE"],"pid":42867,"message":"Deleting orphan watcher: log_error_watch"}
<!code>

kibana.stderr:

<code>
Unhandled rejection TypeError: Cannot read property 'clear' of undefined
    at /opt/kibana/installedPlugins/kaae/server/lib/scheduler.js:32:39
    at arrayEach (/opt/kibana/node_modules/lodash/index.js:1289:13)
    at Function.<anonymous> (/opt/kibana/node_modules/lodash/index.js:3345:13)
    at /opt/kibana/installedPlugins/kaae/server/lib/scheduler.js:30:11
    at tryCatcher (/opt/kibana/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/opt/kibana/node_modules/bluebird/js/main/promise.js:503:31)
    at Promise._settlePromiseAt (/opt/kibana/node_modules/bluebird/js/main/promise.js:577:18)
    at Promise._settlePromises (/opt/kibana/node_modules/bluebird/js/main/promise.js:693:14)
    at Async._drainQueue (/opt/kibana/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/opt/kibana/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/opt/kibana/node_modules/bluebird/js/main/async.js:15:14)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
<!code>

This occurs every minute. 

2. Reproducing the Issue step-by-step:
  Add a watcher or reporter, delete it. The only way I've found to stop this error is to delete KaaE or add a watcher/reporter with the same name.

3. Expected Results vs. Actual Results
  

4. Additional Details
OS: Ubuntu 14.04.3
ES: 2.4.1
Kibana: 4.6.1

**Comment by sethyes** [comment]
uninstalled & reinstalled Kaae again and this issue failed to persist. Closing.

**Comment by lmangani** [comment]
Thanks @sethyes for the report. Let's keep this open for issue reproduction. We should soon redesign the (too simple) mechanism to schedule and remove watchers, by default the orphan vacuum runs just every minute.
