### ISSUE TITLE
MapperParsingException[Field name [...] cannot contain '.'

### ISSUE THREAD

**Issue by maxout123** [elasticfence/kaae#40]
I am trying to get notifications for "topbeat" metrics. As an example, when percent of disk space used is above threshold.

In short, on watcher save I get the error: `MapperParsingException[Field name [fs.used_p] cannot contain '.']`

**Here's the details:**

**The query working in Sense:**
```
GET _search
{
  "query": {
    "filtered": {
      "query": {
        "query_string": {
          "query": "type: filesystem",
          "analyze_wildcard": true
        }
      },
      "filter": {
        "bool": {
          "must": [
            {
              "range": {
                "@timestamp": {
                  "gte": "now-10m",
                  "lte": "now"
                }
              }
            },
            {
              "range": {
                "fs.used_p": {
                  "gte": 0.1
                }
              }
            }
          ],
          "must_not": []
        }
      }
    }
  },
  "size": 1,
  "aggs": {
    "device_name": {
      "terms": {
        "field": "fs.mount_point",
        "size": 100
      },
      "aggs": {
        "used_p": {
          "avg": {
            "field": "fs.used_p"
          }
        }
      }
    }
  }
}
```

**And here is result from ES:**

```
{
  "took": 84,
  "timed_out": false,
  "_shards": {
    "total": 368,
    "successful": 368,
    "failed": 0
  },
  "hits": {
    "total": 2,
    "max_score": 3.1690538,
    "hits": [
      {
        "_index": "topbeat-2016.10.12",
        "_type": "filesystem",
        "_id": "AVe4XqQQLJiUKvRzXlL2",
        "_score": 3.1690538,
        "_source": {
          "type": "filesystem",
          "fs": {
            "device_name": "/dev/vda1",
            "total": 31570522112,
            "used": 4357283840,
            "used_p": 0.14,
            "free": 27213238272,
            "avail": 25585963008,
            "files": 1966080,
            "free_files": 1820159,
            "mount_point": "/"
          },
          "count": 1,
          "beat": {
            "hostname": "h2",
            "name": "h2"
          },
          "@timestamp": "2016-10-12T10:09:50.457Z",
          "@version": "1",
          "host": "h2",
          "tags": [
            "beats_input_raw_event"
          ]
        }
      }
    ]
  },
  "aggregations": {
    "device_name": {
      "doc_count_error_upper_bound": 0,
      "sum_other_doc_count": 0,
      "buckets": [
        {
          "key": "/",
          "doc_count": 2,
          "used_p": {
            "value": 0.14000000059604645
          }
        }
      ]
    }
  }
}
```

Now I am trying to save this watcher in KAAE:

```
{
  "_index": "watcher",
  "_type": "watch",
  "_id": "test",
  "_score": 1,
  "_source": {
    "trigger": {
      "schedule": {
        "later": "every 10 seconds"
      }
    },
    "input": {
      "search": {
        "request": {
          "index": [
            "<topbeat-{now/d}>"
          ],
          "body": {
            "query": {
              "filtered": {
                "query": {
                  "query_string": {
                    "query": "type: filesystem",
                    "analyze_wildcard": true
                  }
                },
                "filter": {
                  "bool": {
                    "must": [
                      {
                        "range": {
                          "@timestamp": {
                            "gte": "now-10m",
                            "lte": "now"
                          }
                        }
                      },
                      {
                        "range": {
                          "fs.used_p": {
                            "gte": 0.1
                          }
                        }
                      }
                    ],
                    "must_not": []
                  }
                }
              }
            }
          }
        }
      }
    },
    "condition": {
      "script": {
        "script": "payload.hits.total > 0"
      }
    },
    "transform": {},
    "actions": {
      "email_admin": {
        "email": {
          "to": "...@gmail.com",
          "from": "kaae@localhost",
          "subject": "KaaE Alarm",
          "priority": "high",
          "body": "Found Events"
        }
      }
    }
  }
}
```

And getting the error:
```
Oct 12 06:04:43  elasticsearch[3462]: [2016-10-12 06:04:43,179][DEBUG][action.admin.indices.mapping.put] [] failed to put mappings on indices [[watcher]], type [watch]
Oct 12 06:04:43  elasticsearch[3462]: MapperParsingException[Field name [fs.used_p] cannot contain '.']
```

But this query works in Sense, and I am stuck with it. Could you please tell me what I am doing wrong and how to achieve my goal?

**Comment by maxout123** [comment]
If it makes any sense, the ES version I am using is 2.4.1

**Comment by lmangani** [comment]
Hi @maxout123 & Thanks for the report! 
This is actually very useful as in theory, 2.4.x should accept fields with dots in names. 
Could you try setting the following mapping preference?
```
export ES_JAVA_OPTS="-Dmapper.allow_dots_in_name=true"
./bin/elasticsearch
```

**Comment by maxout123** [comment]
It helped, thanks!

**Comment by lmangani** [comment]
Thanks for the confirmation! 
We'll most likely switch to treating watchers as string in the future to avoid this being necessary - keeping this open for tracking current solution until included by default.

**Comment by lmangani** [comment]
Hey @maxout123 the build for Kibi now treats the input as object and does not parse it, you might have a use for it on < 2.4 or to avoid the option
Find it here: https://github.com/elasticfence/kaae/releases/download/Kibi-Nightly/kaae-kibi-latest.tar.gz

**Comment by guilhermef** [comment]
@lmangani I'm keep getting the same error:
```
Trace: { [Error: [mapper_parsing_exception] Field name [95.0] cannot contain '.']
  status: 400,
  message: '[mapper_parsing_exception] Field name [95.0] cannot contain \'.\'',
  path: '/watcher_alarms-2016.10.19/email_admin',
  query: { op_type: 'create' },
  body:
   { error:
      { root_cause: [Object],
        type: 'mapper_parsing_exception',
        reason: 'Field name [95.0] cannot contain \'.\'' },
     status: 400 },
  statusCode: 400,
  response: '{"error":{"root_cause":[{"type":"mapper_parsing_exception","reason":"Field name [95.0] cannot contain \'.\'"}],"type":"mapper_parsing_exception","reason":"Field name [95.0] cannot contain \'.\'"},"status":400}',
  toString: [Function],
  toJSON: [Function] } undefined
    at /opt/kibana/installedPlugins/kaae/server/lib/actions.js:77:22
    at tryCatcher (/opt/kibana/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/opt/kibana/node_modules/bluebird/js/main/promise.js:503:31)
    at Promise._settlePromiseAt (/opt/kibana/node_modules/bluebird/js/main/promise.js:577:18)
    at Promise._settlePromises (/opt/kibana/node_modules/bluebird/js/main/promise.js:693:14)
    at Async._drainQueue (/opt/kibana/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/opt/kibana/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/opt/kibana/node_modules/bluebird/js/main/async.js:15:14)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
```

And my watcher:

```
{
  "_index": "watcher",
  "_type": "watch",
  "_id": "MRTS - response time",
  "_score": 1,
  "_source": {
    "trigger": {
      "schedule": {
        "later": "every 1 minute"
      }
    },
    "input": {
      "search": {
        "request": {
          "index": "mrts-stash-*",
          "body": {
            "query": {
              "filtered": {
                "query": {
                  "query_string": {
                    "query": "message:\"Request Done\"",
                    "analyze_wildcard": true
                  }
                },
                "filter": {
                  "range": {
                    "@timestamp": {
                      "from": "now-1h"
                    }
                  }
                }
              }
            },
            "aggs": {
              "response_time": {
                "percentiles": {
                  "field": "time_used",
                  "percents": [
                    95
                  ]
                }
              }
            }
          }
        }
      }
    },
    "condition": {
      "script": {
        "script": "payload.aggregations.response_time.values['95.0'] > 4"
      }
    },
    "transform": {},
    "actions": {
      "email_admin": {
        "throttle_period": "1m",
        "email": {
          "to": "example@example.com",
          "from": "kaae@localhost",
          "subject": "KAAE ALARM {{ payload._id }}",
          "priority": "high",
          "body": "Series Alarm {{ payload._id}}: {{ payload.hits.total }}"
        }
      }
    }
  }
}
```


that's the current mapping:
```
{
  "watcher": {
    "aliases": {

    },
    "mappings": {
      "watch": {
        "properties": {
          "actions": {
            "properties": {
              "email_admin": {
                "properties": {
                  "email": {
                    "properties": {
                      "body": {
                        "type": "string"
                      },
                      "from": {
                        "type": "string"
                      },
                      "priority": {
                        "type": "string"
                      },
                      "subject": {
                        "type": "string"
                      },
                      "to": {
                        "type": "string"
                      }
                    }
                  },
                  "throttle_period": {
                    "type": "string"
                  }
                }
              }
            }
          },
          "condition": {
            "properties": {
              "script": {
                "properties": {
                  "script": {
                    "type": "string"
                  }
                }
              }
            }
          },
          "input": {
            "type": "object",
            "enabled": false
          },
          "transform": {
            "type": "object"
          },
          "trigger": {
            "properties": {
              "schedule": {
                "properties": {
                  "later": {
                    "type": "string"
                  }
                }
              }
            }
          }
        }
      }
    },
    "settings": {
      "index": {
        "creation_date": "1476898562871",
        "uuid": "pdBn74NARpShF8dbi_CkYA",
        "number_of_replicas": "1",
        "number_of_shards": "1",
        "version": {
          "created": "2040099"
        }
      }
    },
    "warmers": {

    }
  }
}
```

**Comment by lmangani** [comment]
Could you try escaping the condition query array value?
```payload.aggregations.response_time.values[\'95.0\'] > 4```

If that fails, we should consider treating all watcher fields as objects as we do for _input_ already.

**Comment by guilhermef** [comment]
The editor doesn't allow me to save a string like:
`"payload.aggregations.response_time.values[\'95.0\'] > 4"`

And I get the same issue with this condition string:
`"payload.aggregations.response_time.values[\"95.0\"] > 4"`

**Comment by lmangani** [comment]
Alright - any chance you can give the mapping change a shot for the ```watcher``` index?
```
          "input": {
            "type": "object",
            "enabled": false
          },
          "transform": {
            "type": "object",
            "enabled": false
          },
```

**Comment by guilhermef** [comment]
sure, I'll do it now

**Comment by guilhermef** [comment]
Still the same error:
```
Trace: { [Error: [mapper_parsing_exception] Field name [95.0] cannot contain '.']
  status: 400,
  message: '[mapper_parsing_exception] Field name [95.0] cannot contain \'.\'',
  path: '/watcher_alarms-2016.10.19/email_admin',
  query: { op_type: 'create' },
  body:
   { error:
      { root_cause: [Object],
        type: 'mapper_parsing_exception',
        reason: 'Field name [95.0] cannot contain \'.\'' },
     status: 400 },
  statusCode: 400,
  response: '{"error":{"root_cause":[{"type":"mapper_parsing_exception","reason":"Field name [95.0] cannot contain \'.\'"}],"type":"mapper_parsing_exception","reason":"Field name [95.0] cannot contain \'.\'"},"status":400}',
  toString: [Function],
  toJSON: [Function] } undefined
    at /opt/kibana/installedPlugins/kaae/server/lib/actions.js:77:22
    at tryCatcher (/opt/kibana/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/opt/kibana/node_modules/bluebird/js/main/promise.js:503:31)
    at Promise._settlePromiseAt (/opt/kibana/node_modules/bluebird/js/main/promise.js:577:18)
    at Promise._settlePromises (/opt/kibana/node_modules/bluebird/js/main/promise.js:693:14)
    at Async._drainQueue (/opt/kibana/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/opt/kibana/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/opt/kibana/node_modules/bluebird/js/main/async.js:15:14)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
```

With mapping:
```
{
  "watcher": {
    "aliases": {

    },
    "mappings": {
      "watch": {
        "properties": {
          "actions": {
            "properties": {
              "email_admin": {
                "properties": {
                  "email": {
                    "properties": {
                      "body": {
                        "type": "string"
                      },
                      "from": {
                        "type": "string"
                      },
                      "priority": {
                        "type": "string"
                      },
                      "subject": {
                        "type": "string"
                      },
                      "to": {
                        "type": "string"
                      }
                    }
                  },
                  "throttle_period": {
                    "type": "string"
                  }
                }
              }
            }
          },
          "condition": {
            "properties": {
              "script": {
                "properties": {
                  "script": {
                    "type": "string"
                  }
                }
              }
            }
          },
          "input": {
            "type": "object",
            "enabled": false
          },
          "transform": {
            "type": "object",
            "enabled": false
          },
          "trigger": {
            "properties": {
              "schedule": {
                "properties": {
                  "later": {
                    "type": "string"
                  }
                }
              }
            }
          }
        }
      }
    },
    "settings": {
      "index": {
        "creation_date": "1476900516020",
        "uuid": "68HhKFGVQ1iQcVN9eFnfQw",
        "number_of_replicas": "1",
        "number_of_shards": "1",
        "version": {
          "created": "2040099"
        }
      }
    },
    "warmers": {

    }
  }
}
```

**Comment by lmangani** [comment]
My bad - you need to do the same for field ```condition```

**Comment by guilhermef** [comment]
It still happens, I'm not sure that the error is related to the watch document.
Looks like It has something to do with the '/watcher_alarms-2016.10.19/email_admin' index.

**Comment by lmangani** [comment]
Alright, this is caused by the ```_source````field it seems. 

The following mapping on the ```watcher_alarms```` should do:
```
mappings: {
                    "_default_": {
                        "_source": { "enabled":  false }
                    }
                  }
```

Could you give it a shot?

**Comment by guilhermef** [comment]
Still the same error, even with:
```
GET /watcher_alarms-2016.10.19

{
  "watcher_alarms-2016.10.19": {
    "aliases": {

    },
    "mappings": {
      "_default_": {
        "_source": {
          "enabled": false
        }
      }
    },
    "settings": {
      "index": {
        "creation_date": "1476911166575",
        "uuid": "KMTHCmW5TLC0DkhnKV06Rg",
        "number_of_replicas": "1",
        "number_of_shards": "5",
        "version": {
          "created": "2040099"
        }
      }
    },
    "warmers": {

    }
  }
}
```

and:

```
GET /watcher_alarms

{
  "watcher_alarms": {
    "aliases": {

    },
    "mappings": {
      "_default_": {
        "_source": {
          "enabled": false
        }
      }
    },
    "settings": {
      "index": {
        "creation_date": "1476911272442",
        "uuid": "9NAQI_E0Q0-SXT1IB3wo9A",
        "number_of_replicas": "1",
        "number_of_shards": "5",
        "version": {
          "created": "2040099"
        }
      }
    },
    "warmers": {

    }
  }
}
```

**Comment by lmangani** [comment]
I work too much. THIS should be it.

```
mappings: {
                    "_default_": {
                        "payload": { "type": "object", "enabled":  false }
                    }
                  }
```

**Comment by guilhermef** [comment]
@lmangani I might be doing something wrong, but I got an invalid response:
```
PUT /watcher_alarms
{
  "mappings": {
    "_default_": {
      "payload": {
        "type": "object",
        "enabled": false
      }
    }
  }
}
```

and got:
```
{
  "error": {
    "root_cause": [
      {
        "type": "mapper_parsing_exception",
        "reason": "Root mapping definition has unsupported parameters:  [payload : {enabled=false, type=object}]"
      }
    ],
    "type": "mapper_parsing_exception",
    "reason": "Failed to parse mapping [_default_]: Root mapping definition has unsupported parameters:  [payload : {enabled=false, type=object}]",
    "caused_by": {
      "type": "mapper_parsing_exception",
      "reason": "Root mapping definition has unsupported parameters:  [payload : {enabled=false, type=object}]"
    }
  },
  "status": 400
}
```

**Comment by guilhermef** [comment]
It worked with:
```
{
  "mappings": {
    "_default_": {
      "properties": {
        "payload": {
          "type": "object",
          "enabled": false
        }
      }
    }
  }
}
```

**Comment by lmangani** [comment]
```
PUT /watcher_alarms
{
  "mappings": {
    "_default_": {
      "payload": {
         properties: {
            "type": "object",
            "enabled": false
         }
      }
    }
  }
}
```

**Comment by guilhermef** [comment]
@lmangani It worked with the properties field outside the payload.

**Comment by lmangani** [comment]
@maxout123 thanks for assisting with testing, now default mapping for the index with d6b6f8e7690288b69d4141884f865990f7d9d4ce

**Comment by guilhermef** [comment]
Thanks @lmangani, you're an awesome maintainer
