### ISSUE TITLE
Message sending failed

### ISSUE THREAD

**Issue by shancang** [elasticfence/kaae#43]
[root@watcher node_modules]# cat /etc/kaae.json 
{
  "es": {
    "timefield":	"@timestamp",
    "default_index":	"watcher",
    "type": 		"watch",
    "alarm_index":	"watcher_alarms"
  },
  "kaae": {
    	"history": 	20,
      "results": 50
  },
  "settings" : {
    	"email" : {
    	   "user":	"monitor",
    	   "password":	"xxxx",
    	   "host":	"smtp.163.com",
    	   "ssl":	false,
    	   "active":	true
    	},
    	"slack" : {
    	   "username":	"KAAE",
    	   "hook":	"https://hooks.slack.com/services/<token>",
    	   "channel":	"#kaae",
    	   "active": 	false
    	},
      "report" : {
         "tmp_path" : "/tmp/",
         "active": 	false
      }
  }
}

ERROR Message 

log   [11:46:00.004] [info][status][KaaE] Executing watch: getFloatPage Next Round of getFloatPage at Thu Oct 13 2016 11:46:00 GMT+0800 (CST)
  log   [11:46:00.031] [info][status][KaaE] Action Report requires Email Settings! Reports Disabled.
  log   [11:46:00.033] [info][status][KaaE] Processing action: email_admin
  log   [11:46:00.034] [info][status][KaaE][email] Subject: KaaE Alarm, Body: Found 192 Events
  log   [11:46:00.037] [info][status][Kaae][email] Delivering to Mail Server
  log   [11:46:00.050] [info][status][Kaae][email] Error: message is not a valid Message instance
    at Object.Client.send (/XXXXX/elk/kibana-4.5.1-linux-x64/installedPlugins/kaae/node_modules/emailjs/smtp/client.js:122:19)
    at /XXXXX/elk/kibana-4.5.1-linux-x64/installedPlugins/kaae/server/lib/actions.js:125:27
    at /XXXXX/elk/kibana-4.5.1-linux-x64/installedPlugins/kaae/node_modules/lodash/index.js:3073:15
    at baseForOwn (/XXXXX/elk/kibana-4.5.1-linux-x64/installedPlugins/kaae/node_modules/lodash/index.js:2046:14)
    at Function.forOwn (/XXXXX/elk/kibana-4.5.1-linux-x64/installedPlugins/kaae/node_modules/lodash/index.js:3378:16)
    at exports.default (/XXXXX/elk/kibana-4.5.1-linux-x64/installedPlugins/kaae/server/lib/actions.js:83:4)
    at /XXXXX/elk/kibana-4.5.1-linux-x64/installedPlugins/kaae/server/lib/scheduler.js:104:23
    at tryCatcher (/XXXXX/elk/kibana-4.5.1-linux-x64/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/XXXXX/elk/kibana-4.5.1-linux-x64/node_modules/bluebird/js/main/promise.js:503:31)
    at Promise._settlePromiseAt (/XXXXX/elk/kibana-4.5.1-linux-x64/node_modules/bluebird/js/main/promise.js:577:18)
    at Promise._settlePromises (/XXXXX/elk/kibana-4.5.1-linux-x64/node_modules/bluebird/js/main/promise.js:693:14)
    at Async._drainQueue (/XXXXX/elk/kibana-4.5.1-linux-x64/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/XXXXX/elk/kibana-4.5.1-linux-x64/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/XXXXX/elk/kibana-4.5.1-linux-x64/node_modules/bluebird/js/main/async.js:15:14)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
  log   [11:46:00.054] [info][status][KaaE] Storing Alarm to ES with type:email_admin

**Comment by lmangani** [comment]
Hi @shancang 
The error ```Error: message is not a valid Message instance``` would suggest you missed either from/to in the body. Please attach your watcher action as well.

**Comment by shancang** [comment]
Thanks
