### ISSUE TITLE
Send Email via local postfix?

### ISSUE THREAD

**Issue by fl0wx** [elasticfence/kaae#46]
1. Issue Description

Hey,

how is it possible to send a mail, if you have a local postfix with configured mailrelayhost?

i always get the following message in the logs:
```

{"type":"log","@timestamp":"2016-10-14T13:55:00+00:00","tags":["status","info","KaaE"],"pid":31651,"message":"Action Report requires Email Settings! Reports Disabled."}
{"type":"log","@timestamp":"2016-10-14T13:55:00+00:00","tags":["status","info","KaaE"],"pid":31651,"message":"Processing action: report_admin"}
{"type":"log","@timestamp":"2016-10-14T13:55:00+00:00","tags":["status","info","KaaE","report"],"pid":31651,"message":"Subject: KaaE Report, Body: Sample KaaE Screenshot Report"}
{"type":"log","@timestamp":"2016-10-14T13:55:00+00:00","tags":["status","info","Kaae","report"],"pid":31651,"message":"Reporting Disabled! No Settings!"}
```

Config:

"email" : {
           "user":      "",
           "password":  "",
           "host":      "nameofmailrelayhost.lan",
           "ssl":       true,
           "active":    true
        },

Greetings,

Flow

**Comment by lmangani** [comment]
Hi @fl0wx 
You can try send to ```localhost``` with ssl disabled. KaaE apparently can't parse or find its settings  ```/etc/kaae.json``` could you confirm it exists?

**Comment by fl0wx** [comment]
Hey, 

i copied the kaae,json to /etc/

stilll get this messages:
```

{"type":"log","@timestamp":"2016-10-15T06:40:00+00:00","tags":["status","info","KaaE"],"pid":31651,"message":"Executing report: reporter_dv1fuh8qi Next round at Sat Oct 15 2016 08:40:00 GMT+0200 (CEST),Sat Oct 15 2016 08:45:00 GMT+0200 (CEST)"}
{"type":"log","@timestamp":"2016-10-15T06:40:00+00:00","tags":["status","info","KaaE"],"pid":31651,"message":"Action Report requires Email Settings! Reports Disabled."}
{"type":"log","@timestamp":"2016-10-15T06:40:00+00:00","tags":["status","info","KaaE"],"pid":31651,"message":"Processing action: report_admin"}
{"type":"log","@timestamp":"2016-10-15T06:40:00+00:00","tags":["status","info","KaaE","report"],"pid":31651,"message":"Subject: KaaE Report, Body: Sample KaaE Screenshot Report"}
{"type":"log","@timestamp":"2016-10-15T06:40:00+00:00","tags":["status","info","Kaae","report"],"pid":31651,"message":"Reporting Disabled! No Settings!"}
```

config:

```
root@server:[/opt/kibana/installedPlugins/kaae]08:41:48:cat /etc/kaae.json
{
  "es": {
    "timefield":        "@timestamp",
    "default_index":    "watcher",
    "type":             "watch",
    "alarm_index":      "watcher_alarms"
  },
  "kaae": {
        "history":      20,
      "results": 50
  },
  "settings" : {
        "email" : {
           "user":      "",
           "password":  "",
           "host":      "localhost",
           "ssl":       false,
           "active":    true
        },
        "slack" : {
           "username":  "KAAE",
           "hook":      "https://hooks.slack.com/services/<token>",
           "channel":   "#kaae",
           "active":    false
        },
      "report" : {
         "tmp_path" : "/tmp/",
         "active":      false
      },
      "pushapps" : {
        "api_key" : "<pushapps API Key>",
        "active":       false
    }
  }
}
```

any suggestions?

**Comment by fl0wx** [comment]
@lmangani : Hey , do you have any news :)? 

Greetings,

Flo

**Comment by lmangani** [comment]
Hi @fl0wx you simply need to enable reporting as well:
```
"report" : {
         "tmp_path" : "/tmp/",
         "active":      true
```

Make sure PhantomJS is installed on the system before trying! ;)

**Comment by fl0wx** [comment]
Hey @lmangani i hat phantomjs installes and report set to active.

Also i set up an watcher to generate an alarm.

i still got no emails.

Log
```

{"type":"log","@timestamp":"2016-10-20T12:44:25+00:00","tags":["status","info","KaaE"],"pid":22882,"message":"Scheduled Watch: new_saved every every 1 minute"}
{"type":"log","@timestamp":"2016-10-20T12:45:00+00:00","tags":["status","info","KaaE"],"pid":22882,"message":"Executing report: reporter_dv1fuh8qi Next round at Thu Oct 20 2016 14:45:00 GMT+0200 (CEST),Thu Oct 20 2016 14:50:00 GMT+0200 (CEST)"}
{"type":"log","@timestamp":"2016-10-20T12:45:00+00:00","tags":["status","info","KaaE"],"pid":22882,"message":"Processing action: report_admin"}
{"type":"log","@timestamp":"2016-10-20T12:45:00+00:00","tags":["status","info","KaaE","report"],"pid":22882,"message":"Subject: KaaE Report, Body: Sample KaaE Screenshot Report"}
{"type":"log","@timestamp":"2016-10-20T12:45:00+00:00","tags":["status","info","Kaae","report"],"pid":22882,"message":"Reporting Disabled! No Settings!"}
{"type":"log","@timestamp":"2016-10-20T12:45:00+00:00","tags":["status","info","KaaE"],"pid":22882,"message":"Executing watch: new_saved Next Round of new_saved at Thu Oct 20 2016 14:45:00 GMT+0200 (CEST),Thu Oct 20 2016 14:46:00 GMT+0200 (CEST)"}
{"type":"log","@timestamp":"2016-10-20T12:45:00+00:00","tags":["status","info","KaaE"],"pid":22882,"message":"Processing action: email_admin"}
{"type":"log","@timestamp":"2016-10-20T12:45:00+00:00","tags":["status","info","KaaE","email"],"pid":22882,"message":"Subject: KAAE ALARM , Body: Series Alarm : 2003"}
{"type":"log","@timestamp":"2016-10-20T12:45:00+00:00","tags":["status","info","Kaae","email"],"pid":22882,"message":"Delivering to Mail Server"}
{"type":"log","@timestamp":"2016-10-20T12:45:00+00:00","tags":["status","info","KaaE"],"pid":22882,"message":"Storing Alarm to ES with type:email_admin"}
{"type":"log","@timestamp":"2016-10-20T12:45:01+00:00","tags":["status","info","Kaae","email"],"pid":22882,"message":"{ attachments: [],\n  alternative: null,\n  header: \n   { 'message-id': '<1476967500753.0.22882@server>',\n     date: 'Thu, 20 Oct 2016 14:45:00 +0200',\n     from: 'kaae@localhost',\n     to: 'xxx',\n     subject: '=?UTF-8?Q?KAAE_ALARM_?=' },\n  content: 'text/plain; charset=utf-8',\n  text: 'Series Alarm : 2003' }"}
```

suggestions?

**Comment by lmangani** [comment]
Hi @fl0wx 
Reports are still disabled, probably due to missing settings: ```{"type":"log","@timestamp":"2016-10-20T12:45:00+00:00","tags":["status","info","Kaae","report"],"pid":22882,"message":"Reporting Disabled! No Settings!"}
```

The mail delivery to postfix is something else - maybe you can have it accept smtp?

**Comment by fl0wx** [comment]
@lmangani how can i enable them? i set active to true in /etc/kaae,json and also in the kibana directory. 

i dont understand why the mailing via the relayhost isnt working. i tried following configs:

```
 "email" : {
           "user":      "",
           "password":  "",
           "host":      "mailrelayhost",
           "port":      25,
           "ssl":       false,
           "active":    true
        },
```

and 

```
 "email" : {
           "user":      "",
           "password":  "",
           "host":      "localhost",
           "ssl":       false,
           "active":    true
        },
```
the first one generates following error:

```
{"type":"log","@timestamp":"2016-10-20T13:48:00+00:00","tags":["status","info","KaaE"],"pid":24848,"message":"Storing Alarm to ES with type:email_admin"}
{"type":"log","@timestamp":"2016-10-20T13:48:00+00:00","tags":["status","info","Kaae","email"],"pid":24848,"level":"error","message":"bad response on command 'RCPT': Temporary local problem - please try later","error":{"message":"bad response on command 'RCPT': Temporary local problem - please try later","name":"Error","stack":"Error: bad response on command 'RCPT': Temporary local problem - please try later\n    at module.exports (/opt/kibana/installedPlugins/kaae/node_modules/emailjs/smtp/error.js:3:13)\n    at response (/opt/kibana/installedPlugins/kaae/node_modules/emailjs/smtp/smtp.js:207:28)\n    at caller (/opt/kibana/installedPlugins/kaae/node_modules/emailjs/smtp/smtp.js:48:14)\n    at Socket.response (/opt/kibana/installedPlugins/kaae/node_modules/emailjs/smtp/smtp.js:181:11)\n    at Socket.g (events.js:260:16)\n    at emitTwo (events.js:87:13)\n    at Socket.emit (events.js:172:7)\n    at notify (/opt/kibana/installedPlugins/kaae/node_modules/emailjs/smtp/response.js:19:14)\n    at Socket.watch (/opt/kibana/installedPlugins/kaae/node_modules/emailjs/smtp/response.js:44:7)\n    at emitOne (events.js:77:13)\n    at Socket.emit (events.js:169:7)\n    at readableAddChunk (_stream_readable.js:153:18)\n    at Socket.Readable.push (_stream_readable.js:111:10)\n    at TCP.onread (net.js:536:20)","code":2}}
```

sending emails via sendmail on bash is working without any problems.

Greetings FLo

**Comment by lmangani** [comment]
@fl0wx I wish I could help but this is more of a local settings issue - the error KaaE/emailjs receives from your server is ```bad response on command 'RCPT': Temporary local problem - please try later```

You might want to try experiment with a small nodejs/emailjs script locally and once you get a working solution, I'd be happy to make it easy to configure in KaaE if needed?

**Comment by fl0wx** [comment]
@lmangani : i will try emailjs  - smtp cleint. is that the right one?

I will report to you, if i get a working example

**Comment by lmangani** [comment]
Many Thanks! 

We'll reopen this issue as soon as you have some data/examples we can integrate
