### ISSUE TITLE
Cannot find kaae in my Kibana 

### ISSUE THREAD

**Issue by kayrus** [elasticfence/kaae#49]
I've installed the plugin:

```
/bin/kibana plugin --install kaae -u https://github.com/elasticfence/kaae/releases/download/snapshot/kaae-latest.tar.gz
```

Started Kibana, got this error message:

```
{"type":"log","@timestamp":"2016-10-18T17:35:20Z","tags":["status","plugin:kibana@1.0.0","info"],"pid":12,"state":"green","message":"Status changed from uninitialized to green - Ready","prevState":"uninitialized","prevMsg":"uninitialized"}
{"type":"log","@timestamp":"2016-10-18T17:35:20Z","tags":["status","plugin:elasticsearch@1.0.0","info"],"pid":12,"state":"yellow","message":"Status changed from uninitialized to yellow - Waiting for Elasticsearch","prevState":"uninitialized","prevMsg":"uninitialized"}
{"type":"log","@timestamp":"2016-10-18T17:35:20Z","tags":["status","info","KaaE"],"pid":12,"message":"KaaE Initializing"}
{"type":"log","@timestamp":"2016-10-18T17:35:21Z","tags":["status","info","KaaE"],"pid":12,"message":"Core Index check..."}
{"type":"log","@timestamp":"2016-10-18T17:35:21Z","tags":["status","info","KaaE"],"pid":12,"message":"Alarm Index check..."}
{"type":"log","@timestamp":"2016-10-18T17:35:21Z","tags":["status","plugin:kaae@0.0.9","info"],"pid":12,"state":"green","message":"Status changed from uninitialized to green - Ready","prevState":"uninitialized","prevMsg":"uninitialized"}
Unhandled rejection [index_not_found_exception] no such index, with: {"resource.type":"index_or_alias","resource.id":"watcher","index":"watcher"} :: {"path":"/watcher/watch/_count","query":{},"statusCode":404,"response":"{\"error\":{\"root_cause\":[{\"type\":\"index_not_found_exception\",\"reason\":\"no such index\",\"resource.type\":\"index_or_alias\",\"resource.id\":\"watcher\",\"index\":\"watcher\"}],\"type\":\"index_not_found_exception\",\"reason\":\"no such index\",\"resource.type\":\"index_or_alias\",\"resource.id\":\"watcher\",\"index\":\"watcher\"},\"status\":404}"}
    at respond (/kibana-linux-x86_64/node_modules/elasticsearch/src/lib/transport.js:238:15)
    at checkRespForFailure (/kibana-linux-x86_64/node_modules/elasticsearch/src/lib/transport.js:201:7)
    at HttpConnector.<anonymous> (/kibana-linux-x86_64/node_modules/elasticsearch/src/lib/connectors/http.js:155:7)
    at IncomingMessage.wrapper (/kibana-linux-x86_64/node_modules/lodash/index.js:3095:19)
    at emitNone (events.js:85:20)
    at IncomingMessage.emit (events.js:179:7)
    at endReadableNT (_stream_readable.js:913:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)
{"type":"log","@timestamp":"2016-10-18T17:35:21Z","tags":["status","plugin:kbn_vislib_vis_types@1.0.0","info"],"pid":12,"state":"green","message":"Status changed from uninitialized to green - Ready","prevState":"uninitialized","prevMsg":"uninitialized"}
{"type":"log","@timestamp":"2016-10-18T17:35:21Z","tags":["status","plugin:markdown_vis@1.0.0","info"],"pid":12,"state":"green","message":"Status changed from uninitialized to green - Ready","prevState":"uninitialized","prevMsg":"uninitialized"}
{"type":"log","@timestamp":"2016-10-18T17:35:21Z","tags":["status","plugin:metric_vis@1.0.0","info"],"pid":12,"state":"green","message":"Status changed from uninitialized to green - Ready","prevState":"uninitialized","prevMsg":"uninitialized"}
{"type":"log","@timestamp":"2016-10-18T00:00:00Z","tags":["status","info","KaaE"],"pid":12,"message":"Core Index response"}
{"type":"log","@timestamp":"2016-10-18T17:35:21Z","tags":["status","plugin:spyModes@1.0.0","info"],"pid":12,"state":"green","message":"Status changed from uninitialized to green - Ready","prevState":"uninitialized","prevMsg":"uninitialized"}
{"type":"log","@timestamp":"2016-10-18T17:35:21Z","tags":["status","plugin:statusPage@1.0.0","info"],"pid":12,"state":"green","message":"Status changed from uninitialized to green - Ready","prevState":"uninitialized","prevMsg":"uninitialized"}
{"type":"log","@timestamp":"2016-10-18T17:35:21Z","tags":["status","plugin:table_vis@1.0.0","info"],"pid":12,"state":"green","message":"Status changed from uninitialized to green - Ready","prevState":"uninitialized","prevMsg":"uninitialized"}
{"type":"log","@timestamp":"2016-10-18T17:35:21Z","tags":["listening","info"],"pid":12,"message":"Server running at http://0.0.0.0:5601"}
{"type":"log","@timestamp":"2016-10-18T17:35:21Z","tags":["status","plugin:elasticsearch@1.0.0","info"],"pid":12,"state":"green","message":"Status changed from yellow to green - Kibana index ready","prevState":"yellow","prevMsg":"Waiting for Elasticsearch"}
{"type":"log","@timestamp":"2016-10-18T00:00:00Z","tags":["status","info","KaaE"],"pid":12,"message":"Alarm Index response"}
```

And I don't see anything in my Kibana. How can I open this fancy web interface? Did I miss something?

**Comment by lmangani** [comment]
Hi @kayrus 
We need some more details:

- What version of Kibana are you running
- Do you have any other plugins installed and visible (Sense, Timelion, etc)?

**Comment by kayrus** [comment]
@lmangani Kibana 4.6.1
There are no extra plugins expect kaae.

When I restarted kibana I got these logs (previous index error message log disappeared):

```
{"type":"log","@timestamp":"2016-10-18T17:56:46Z","tags":["status","plugin:kibana@1.0.0","info"],"pid":12,"state":"green","message":"Status changed from uninitialized to green - Ready","prevState":"uninitialized","prevMsg":"uninitialized"}
{"type":"log","@timestamp":"2016-10-18T17:56:46Z","tags":["status","plugin:elasticsearch@1.0.0","info"],"pid":12,"state":"yellow","message":"Status changed from uninitialized to yellow - Waiting for Elasticsearch","prevState":"uninitialized","prevMsg":"uninitialized"}
{"type":"log","@timestamp":"2016-10-18T17:56:47Z","tags":["status","info","KaaE"],"pid":12,"message":"KaaE Initializing"}
{"type":"log","@timestamp":"2016-10-18T17:56:47Z","tags":["status","info","KaaE"],"pid":12,"message":"Core Index check..."}
{"type":"log","@timestamp":"2016-10-18T17:56:47Z","tags":["status","info","KaaE"],"pid":12,"message":"Alarm Index check..."}
{"type":"log","@timestamp":"2016-10-18T17:56:47Z","tags":["status","plugin:kaae@0.0.9","info"],"pid":12,"state":"green","message":"Status changed from uninitialized to green - Ready","prevState":"uninitialized","prevMsg":"uninitialized"}
{"type":"log","@timestamp":"2016-10-18T17:56:47Z","tags":["status","plugin:kbn_vislib_vis_types@1.0.0","info"],"pid":12,"state":"green","message":"Status changed from uninitialized to green - Ready","prevState":"uninitialized","prevMsg":"uninitialized"}
{"type":"log","@timestamp":"2016-10-18T17:56:47Z","tags":["status","plugin:markdown_vis@1.0.0","info"],"pid":12,"state":"green","message":"Status changed from uninitialized to green - Ready","prevState":"uninitialized","prevMsg":"uninitialized"}
{"type":"log","@timestamp":"2016-10-18T17:56:47Z","tags":["status","plugin:metric_vis@1.0.0","info"],"pid":12,"state":"green","message":"Status changed from uninitialized to green - Ready","prevState":"uninitialized","prevMsg":"uninitialized"}
{"type":"log","@timestamp":"2016-10-18T17:56:47Z","tags":["status","plugin:spyModes@1.0.0","info"],"pid":12,"state":"green","message":"Status changed from uninitialized to green - Ready","prevState":"uninitialized","prevMsg":"uninitialized"}
{"type":"log","@timestamp":"2016-10-18T17:56:48Z","tags":["status","plugin:statusPage@1.0.0","info"],"pid":12,"state":"green","message":"Status changed from uninitialized to green - Ready","prevState":"uninitialized","prevMsg":"uninitialized"}
{"type":"log","@timestamp":"2016-10-18T17:56:48Z","tags":["status","plugin:table_vis@1.0.0","info"],"pid":12,"state":"green","message":"Status changed from uninitialized to green - Ready","prevState":"uninitialized","prevMsg":"uninitialized"}
{"type":"log","@timestamp":"2016-10-18T17:56:48Z","tags":["listening","info"],"pid":12,"message":"Server running at http://0.0.0.0:5601"}
{"type":"log","@timestamp":"2016-10-18T17:56:48Z","tags":["status","plugin:elasticsearch@1.0.0","info"],"pid":12,"state":"green","message":"Status changed from yellow to green - Kibana index ready","prevState":"yellow","prevMsg":"Waiting for Elasticsearch"}
```

But I still don't see anything. Should I use special location or what? Like http://my-kibana:5601/_plugins/kaae?

**Comment by lmangani** [comment]
Did you click the Kibana Apps menu or is it missing?

<img src="https://docs.ovh.com/docs/mobile-hosting/logs/using_timelion_with_logs/images/timelion.png">

**Comment by kayrus** [comment]
I don't have anything. Just opened kibana in incognito mode and there is still nothing.
![screenshot_20161018_200458](https://cloud.githubusercontent.com/assets/4047483/19490116/2a7c589c-956e-11e6-9f0a-b7e82dcc8dda.png)

**Comment by lmangani** [comment]
What happens if you browse to ```/app/kaae``` ?

**Comment by kayrus** [comment]
```
{"statusCode":404,"error":"Not Found","message":"Unknown app kaae"}
```

**Comment by kayrus** [comment]
Just in case:

```sh
$ find /kibana-linux-x86_64 -name '*kaae*'
/kibana-linux-x86_64/installedPlugins/kaae
/kibana-linux-x86_64/installedPlugins/kaae/public/kaae_watch.svg
/kibana-linux-x86_64/installedPlugins/kaae/public/kaae.svg
/kibana-linux-x86_64/installedPlugins/kaae/public/kaae_logo.svg
/kibana-linux-x86_64/installedPlugins/kaae/kaae.json
/kibana-linux-x86_64/optimize/bundles/installedPlugins/kaae
/kibana-linux-x86_64/optimize/bundles/installedPlugins/kaae/public/kaae_watch.svg
/kibana-linux-x86_64/optimize/bundles/installedPlugins/kaae/public/kaae.svg
/kibana-linux-x86_64/optimize/bundles/kaae.entry.js
/kibana-linux-x86_64/optimize/bundles/kaae.style.css
/kibana-linux-x86_64/optimize/bundles/kaae.bundle.js
```

**Comment by lmangani** [comment]
Very odd. Could you try install another official plugin, such as sense?
```
/bin/kibana plugin --install elastic/sense 
```

**Comment by kayrus** [comment]
```sh
/kibana-linux-x86_64/bin/kibana plugin --install elastic/sense
Installing sense
Attempting to transfer from https://download.elastic.co/elastic/sense/sense-latest.tar.gz
Transferring 1386775 bytes....................
Transfer complete
Extracting plugin archive
Extraction complete
Optimizing and caching browser bundles...
Plugin installation complete
```

Then still nothing:

```sh
$ curl http://localhost:5601/app/sense
{"statusCode":404,"error":"Not Found","message":"Unknown app sense"}
```

Does it make sense that I run it inside the docker container which is based on `mhart/alpine-node:5` ?

**Comment by lmangani** [comment]
If ```sense``` is also not showing up, this might not be a ```KaaE``  issue but rather a general one. 
This might sound silly but are you 100% positive you're accessing the same Kibana instance you are installing plugins to?

I just downloaded a bare 4.6.1, installed KaaE and it shows up immediately on restart

**Comment by lmangani** [comment]
Closing the ticket not to confuse others, please do feel free to continue your troubleshooting here until solved for suggestions

**Comment by kayrus** [comment]
Yes, I mixed up environments. Thanks for your fast response. Have to go home :)

**Comment by lmangani** [comment]
Glad you got it sorted - Enjoy the rest of your day ;)
